openapi: "3.1.0"
info:
  title: Eval Hub BFF API
  description: |
    Backend-for-Frontend API contract for the Evaluations UI package.
    This BFF proxies authenticated requests from the RHOAI Dashboard frontend to
    the external Eval Hub control plane REST API.
    All routes are prefixed with /api and served by the eval-hub BFF on port 8343.
  version: "0.1.0"
  license:
    name: Apache 2.0

servers:
  - url: http://localhost:8343/api
    description: Local development (BFF)
  - url: /eval-hub/api
    description: Production (proxied via ODH Dashboard federation)

tags:
  - name: evaluations
    description: Evaluation job management
  - name: collections
    description: Evaluation collection browsing
  - name: benchmarks
    description: Individual benchmark browsing
  - name: providers
    description: Evaluation provider listing
  - name: health
    description: Health check

paths:

  # ─── Health ──────────────────────────────────────────────────────────────────

  /v1/health:
    get:
      operationId: getHealth
      tags: [health]
      summary: Health check — includes MLFlow component status
      responses:
        "200":
          description: Health status
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthResponse"
        "503":
          description: Service unhealthy
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  # ─── Evaluations ─────────────────────────────────────────────────────────────

  /v1/evaluations/jobs:
    get:
      operationId: listEvaluations
      tags: [evaluations]
      summary: List evaluation runs (paginated, filterable by status)
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 50
          description: Maximum number of items to return
        - name: offset
          in: query
          schema:
            type: integer
            minimum: 0
            default: 0
          description: Pagination offset
        - name: status_filter
          in: query
          schema:
            type: string
            enum: [pending, running, completed, failed, cancelled]
          description: Filter by run status
      responses:
        "200":
          description: Paginated list of evaluation runs
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EvaluationJobList"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "502":
          $ref: "#/components/responses/BadGateway"

    post:
      operationId: createEvaluation
      tags: [evaluations]
      summary: Create and submit a new evaluation run
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateEvaluationRequest"
      responses:
        "202":
          description: Evaluation job accepted and queued
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EvaluationJob"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "502":
          $ref: "#/components/responses/BadGateway"

  /v1/evaluations/jobs/{id}:
    get:
      operationId: getEvaluation
      tags: [evaluations]
      summary: Get a single evaluation run by ID (including results when complete)
      parameters:
        - $ref: "#/components/parameters/IdPath"
      responses:
        "200":
          description: Evaluation run detail
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EvaluationJob"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFound"
        "502":
          $ref: "#/components/responses/BadGateway"

    delete:
      operationId: cancelEvaluation
      tags: [evaluations]
      summary: Cancel a running or pending evaluation
      parameters:
        - $ref: "#/components/parameters/IdPath"
      responses:
        "204":
          description: Evaluation cancelled successfully
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFound"
        "409":
          description: Evaluation is already in a terminal state
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "502":
          $ref: "#/components/responses/BadGateway"

  # ─── Collections ─────────────────────────────────────────────────────────────

  /v1/evaluations/collections:
    get:
      operationId: listCollections
      tags: [collections]
      summary: List all available evaluation collections
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 50
        - name: offset
          in: query
          schema:
            type: integer
            minimum: 0
            default: 0
      responses:
        "200":
          description: List of evaluation collections
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CollectionList"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "502":
          $ref: "#/components/responses/BadGateway"

  /v1/evaluations/collections/{id}:
    get:
      operationId: getCollection
      tags: [collections]
      summary: Get a single collection with its full benchmark list
      parameters:
        - $ref: "#/components/parameters/IdPath"
      responses:
        "200":
          description: Collection detail
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Collection"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFound"
        "502":
          $ref: "#/components/responses/BadGateway"

  # ─── Providers & Benchmarks ──────────────────────────────────────────────────

  /v1/evaluations/providers:
    get:
      operationId: listProviders
      tags: [providers, benchmarks]
      summary: List providers and their supported benchmarks
      parameters:
        - name: include_benchmarks
          in: query
          schema:
            type: boolean
            default: true
          description: Include benchmark list per provider
      responses:
        "200":
          description: List of providers with benchmarks
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProvidersResponse"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
        "502":
          $ref: "#/components/responses/BadGateway"

# ─── Components ──────────────────────────────────────────────────────────────

components:

  parameters:
    IdPath:
      name: id
      in: path
      required: true
      schema:
        type: string

  responses:
    BadRequest:
      description: Bad request — invalid input
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
    Unauthorized:
      description: Unauthorized — missing or invalid token
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
    Forbidden:
      description: Forbidden — insufficient permissions
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
    BadGateway:
      description: Upstream Eval Hub API unreachable or returned an error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"

  schemas:

    ErrorResponse:
      type: object
      required: [message, message_code]
      properties:
        message:
          type: string
        message_code:
          type: string
        trace:
          type: string

    HealthResponse:
      type: object
      required: [status]
      properties:
        status:
          type: string
          enum: [healthy, degraded, unhealthy]
        version:
          type: string
        timestamp:
          type: string
          format: date-time
        components:
          type: object
          additionalProperties:
            type: object
          description: |
            Component health map. Key "mlflow" indicates MLFlow availability.
            If "mlflow" is absent or status != "healthy", the UI must show the
            MLFlow-not-enabled empty state.
        uptime:
          type: number
        active_evaluations:
          type: integer

    # ── Pagination wrapper ────────────────────────────────────────────────────

    Pagination:
      type: object
      properties:
        first:
          $ref: "#/components/schemas/HRef"
        next:
          $ref: "#/components/schemas/HRef"
        limit:
          type: integer
        total_count:
          type: integer

    HRef:
      type: object
      properties:
        href:
          type: string

    # ── Shared primitives ─────────────────────────────────────────────────────

    EvaluationStatus:
      type: string
      enum: [pending, running, completed, failed, cancelled]

    Message:
      type: object
      properties:
        message:
          type: string
        message_code:
          type: string

    ModelRef:
      type: object
      required: [url, name]
      properties:
        url:
          type: string
          format: uri
        name:
          type: string

    PassCriteria:
      type: object
      properties:
        threshold:
          type: number
          minimum: 0
          maximum: 100

    CollectionRef:
      type: object
      required: [id]
      properties:
        id:
          type: string

    PrimaryScore:
      type: object
      properties:
        metric:
          type: string
        lower_is_better:
          type: boolean

    BenchmarkConfig:
      type: object
      required: [id, provider_id]
      properties:
        id:
          type: string
        provider_id:
          type: string
        weight:
          type: number
          default: 1
        primary_score:
          $ref: "#/components/schemas/PrimaryScore"
        pass_criteria:
          $ref: "#/components/schemas/PassCriteria"
        parameters:
          type: object

    # ── Evaluation Job ────────────────────────────────────────────────────────

    JobResource:
      type: object
      required: [id, tenant, created_at, updated_at]
      properties:
        id:
          type: string
        tenant:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        mlflow_experiment_id:
          type: string
        message:
          $ref: "#/components/schemas/Message"

    BenchmarkJobStatus:
      type: object
      properties:
        provider_id:
          type: string
        id:
          type: string
        status:
          $ref: "#/components/schemas/EvaluationStatus"
        error_message:
          $ref: "#/components/schemas/Message"
        started_at:
          type: string
          format: date-time
        completed_at:
          type: string
          format: date-time

    JobStatus:
      type: object
      required: [state]
      properties:
        state:
          $ref: "#/components/schemas/EvaluationStatus"
        message:
          $ref: "#/components/schemas/Message"
        benchmarks:
          type: array
          items:
            $ref: "#/components/schemas/BenchmarkJobStatus"

    BenchmarkResult:
      type: object
      properties:
        id:
          type: string
        provider_id:
          type: string
        metrics:
          type: object
        artifacts:
          type: object
        mlflow_run_id:
          type: string
        logs_path:
          type: string

    JobResults:
      type: object
      properties:
        benchmarks:
          type: array
          items:
            $ref: "#/components/schemas/BenchmarkResult"
        mlflow_experiment_url:
          type: string
          format: uri
          description: |
            Deep link to the MLFlow experiment for this evaluation run.
            Null/absent when MLFlow is not enabled or the experiment was not created.

    EvaluationJob:
      type: object
      required: [resource, status, model, benchmarks]
      properties:
        resource:
          $ref: "#/components/schemas/JobResource"
        status:
          $ref: "#/components/schemas/JobStatus"
        results:
          $ref: "#/components/schemas/JobResults"
        model:
          $ref: "#/components/schemas/ModelRef"
        pass_criteria:
          $ref: "#/components/schemas/PassCriteria"
        benchmarks:
          type: array
          items:
            $ref: "#/components/schemas/BenchmarkConfig"
        collection:
          $ref: "#/components/schemas/CollectionRef"

    EvaluationJobList:
      allOf:
        - $ref: "#/components/schemas/Pagination"
        - type: object
          required: [items]
          properties:
            items:
              type: array
              items:
                $ref: "#/components/schemas/EvaluationJob"

    CreateEvaluationRequest:
      type: object
      required: [model, benchmarks]
      properties:
        model:
          $ref: "#/components/schemas/ModelRef"
        pass_criteria:
          $ref: "#/components/schemas/PassCriteria"
        benchmarks:
          type: array
          minItems: 1
          items:
            $ref: "#/components/schemas/BenchmarkConfig"
        collection:
          $ref: "#/components/schemas/CollectionRef"
        custom:
          type: object
          description: |
            Additional user-provided arguments (from optional JSON upload).
            Forwarded as-is to Eval Hub.

    # ── Collections ───────────────────────────────────────────────────────────

    CollectionResource:
      type: object
      required: [id, tenant, created_at, updated_at]
      properties:
        id:
          type: string
        tenant:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    Collection:
      type: object
      required: [resource, type, name, description, tags, benchmarks]
      properties:
        resource:
          $ref: "#/components/schemas/CollectionResource"
        type:
          type: string
          enum: [system, user]
        name:
          type: string
        description:
          type: string
        tags:
          type: array
          items:
            type: string
          description: Industry/use-case tags, e.g. ["Healthcare", "Safety"]
        custom:
          type: object
        pass_criteria:
          $ref: "#/components/schemas/PassCriteria"
        benchmarks:
          type: array
          items:
            $ref: "#/components/schemas/BenchmarkConfig"

    CollectionList:
      allOf:
        - $ref: "#/components/schemas/Pagination"
        - type: object
          required: [items]
          properties:
            items:
              type: array
              items:
                $ref: "#/components/schemas/Collection"

    # ── Providers & Benchmarks ────────────────────────────────────────────────

    BenchmarkDefinition:
      type: object
      properties:
        id:
          type: string
        provider_id:
          type: string
        name:
          type: string
        description:
          type: string
        category:
          type: string
        metrics:
          type: array
          items:
            type: string
        num_few_shot:
          type: integer
        dataset_size:
          type: integer
        tags:
          type: array
          items:
            type: string

    Provider:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        type:
          type: string
        benchmarks:
          type: array
          items:
            $ref: "#/components/schemas/BenchmarkDefinition"

    ProvidersResponse:
      type: object
      required: [total_count, items]
      properties:
        total_count:
          type: integer
        items:
          type: array
          items:
            $ref: "#/components/schemas/Provider"

